#!/usr/bin/env python

def encode(data):
    return ' '.join([bin(ord(c))[2:].zfill(8) for c in data])

if __name__ == '__main__':
    import sys
    for line in sys.stdin:
        print encode(line.strip())
