#!/usr/bin/env python

def encode(data):
    return ''.join([chr(int(x, 16)) for x in data.split()])

if __name__ == '__main__':
  import sys
  for line in sys.stdin:
      print(encode(line.strip()))
