#!/usr/bin/env python

def decode(data):
    return ' '.join(['%02X' % ord(c) for c in data])

if __name__ == '__main__':
    import sys
    for line in sys.stdin:
        print(decode(line.strip()))
